-- Directory taxonomy: structured classification for the public directory.
-- Additive only — the legacy free-text `category` column is untouched and still
-- feeds display + the groupOf() fallback for unclassified rows.
--   wrangler d1 execute townsquare --remote --file=migrate-taxonomy.sql -y
--
-- primary_category  one of 9 stable slugs (eat-drink, stay, shop, things-to-do,
--                   beauty-wellness, home-auto, local-services, community,
--                   events-venues); NULL = not yet classified (falls back to the
--                   legacy client-side mapping, and appears in the admin review list)
-- subcategory       optional slug scoped to the primary; NULL = unspecified
-- tags              JSON array of descriptive tag strings from the fixed allow-list
--                   (Family Friendly / Pet Friendly / Appointment Required live in
--                   their own existing columns and are NOT duplicated here)
--
-- Content backfill lives in migrate-taxonomy-backfill.sql (generated by
-- scripts/classify-businesses.mjs) and runs separately, AFTER this.

ALTER TABLE businesses ADD COLUMN primary_category TEXT;
ALTER TABLE businesses ADD COLUMN subcategory TEXT;
ALTER TABLE businesses ADD COLUMN tags TEXT;

CREATE INDEX IF NOT EXISTS idx_biz_primary_category ON businesses (primary_category);
